SMALL_INDUSTRIAL_STYLE = """A 60 second industrial rock / EBM song section in the spirit of early KMFDM and Nitzer Ebb, with aggressive shouted and chanted vocals that feel like a call-to-arms. The tempo is around 130 BPM with a rigid 4-on-the-floor kick drum, a hard snare on 2 and 4, and crisp hi-hats pushing the groove forward like a relentless machine. Distorted electric guitars play tight, repetitive riffs built on a minor-key progression, mostly power chords and octave riffs with very little harmonic movement, emphasizing rhythm, crunch, and attitude over melody. The bassline is simple, pounding, and mechanical, often repeating a short pattern that locks perfectly with the kick drum, giving the feeling of a marching EBM bass sequence.

On top of this, there is a male lead vocal that is not melodic singing but harsh, rhythmic shouting and chanting, like a political megaphone or an angry crowd leader. The vocal is heavily processed: slightly distorted, compressed, and pushed forward in the mix so it cuts through the guitars and drums. The vocal phrases are short, repetitive, and slogan-like, as if they could be shouted back by a live audience, with occasional gang-style chants reinforcing key lines. There are no soft, breathy, or pop-style vocals; everything is rough, commanding, and percussive.

The drums feel like an electronic drum machine combined with industrial samples: kicks and snares are saturated and clipped, toms and cymbals are minimal, and there are metallic hits and clanging sounds accenting the rhythm. Occasional noise sweeps, machine sounds, and glitchy stutters appear between vocal lines to keep the energy high. The overall mix is dry, brickwalled, and mid-heavy, with very little reverb or spatial ambience, evoking a small concrete club or warehouse rather than a big cinematic hall. There are absolutely no orchestral strings, no lush pads, no cinematic drones, no jazz instruments; the palette is strictly distorted guitars, drum machine, bass, aggressive shouted vocals, and a few harsh synth or metallic stabs to underline the industrial character."""

MEDIUM_INDUSTRIAL_STYLE = """A 30 second instrumental industrial rock / EBM section at 160 BPM, extremely hard and aggressive, clearly inspired by early KMFDM backing tracks. Rigid 4-on-the-floor kick (every beat) from a punchy electronic drum machine, with a very hard snare on 2 and 4 and crisp, driving hi-hats. Occasional short tom fills or extra hits are allowed, but the core pattern must stay strict and marching.

Main instruments: distorted rhythm electric guitars, electronic drum machine, and a simple but powerful bass synth or bass guitar. The guitars play tight, palm-muted power-chord riffs in a minor key, chugging eight notes or sixteenths that lock perfectly to the kick drum. No solos, no melodic leads, just brutal rhythm guitar riffs. The bass follows or doubles the guitar riff, with a gritty, mechanical tone that feels like an EBM bass sequence, reinforcing the drive of the drums.

The sound is dry, loud, and heavily compressed, almost brickwalled, like an industrial band playing in a small concrete bunker. Very little reverb, no big spaces, no cinematic ambience. No vocals of any kind. Absolutely no choirs, no organs, no strings, no pads, no piano, no orchestral or ambient textures, no soundscapes, no atmospheric swells. Only drum machine, distorted rhythm guitars, bass, and maybe a few very short metallic synth stabs or noise bursts accenting strong beats. The overall impression should be a fast, brutal, tightly locked KMFDM-style instrumental section that could sit in the middle of a high-intensity industrial rock track."""

LARGE_KMFDMLIKE_STYLE = """
10 second instrumental industrial rock / EDM section at 160 BPM, extremely hard and aggressive, clearly inspired by early KMFDM backing tracks. Rigid 4-on-the-floor electronic kick on every beat, very hard snare on 2 and 4, crisp hi-hats. Distorted rhythm guitars playing tight, repetitive power-chord riffs in a minor key, locked to the drums, plus a simple mechanical bassline doubling the riff. Dry, loud, heavily compressed mix, like a drum machine and guitars in a small concrete bunker. No vocals, no choirs, no organs, no strings, no pads, no orchestral or cinematic sounds, no ambient textures, no soundscapes. Only drum machine, distorted rhythm guitars, bass, and maybe one or two very short metallic synth hits.
""".strip()
